#!/usr/bin/env bash
# Install launchd watchdog (runs every 5 min, also at login).
# Launcher lives in ~/bin (outside Documents) to avoid macOS TCC blocking launchd.
#
# CRITICAL (2026-07-12 lessons):
# 1. Never derive ROOT from `dirname "$0"` when the launcher lives in ~/bin
#    (resolved to /Users/tom → Terminal window storm).
# 2. Launchd must not need to execute or write under ~/Documents (TCC exit 126 /
#    Operation not permitted). The ~/bin launcher only: reads pause/cooldown in
#    ~/Library/Logs, pgreps, and osascripts Terminal to start bulk with Documents access.
#
# Verify:
#   launchctl print gui/$UID/com.alphaw0lf.ford-bulk-watchdog
#   ~/Library/Logs/ford-bulk-watchdog.log
#
# Usage:
#   ./scripts/install-bulk-watchdog.sh
#   ./scripts/install-bulk-watchdog.sh --uninstall
set -eo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LABEL="com.alphaw0lf.ford-bulk-watchdog"
PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
UID_NUM="$(id -u)"
SYS_LOG_DIR="$HOME/Library/Logs"
SYS_LOG="${SYS_LOG_DIR}/ford-bulk-watchdog.log"
SYS_PAUSE="${SYS_LOG_DIR}/ford-bulk-watchdog.pause"
SYS_COOLDOWN="${SYS_LOG_DIR}/ford-bulk-watchdog-last-restart.txt"

if [[ "${1:-}" == "--uninstall" ]]; then
  launchctl bootout "gui/${UID_NUM}" "$PLIST" 2>/dev/null || true
  rm -f "$PLIST"
  echo "Uninstalled $LABEL"
  exit 0
fi

if [[ ! -f "$ROOT/scripts/bulk-download.sh" || ! -f "$ROOT/scripts/start-bulk-download.sh" ]]; then
  echo "ERROR: invalid repo root $ROOT (missing bulk scripts)" >&2
  exit 1
fi

mkdir -p "$ROOT/logs" "$HOME/Library/LaunchAgents" "$HOME/bin" "$SYS_LOG_DIR"

LAUNCHER="$HOME/bin/ford-bulk-watchdog.sh"
# TCC-safe launcher: no cd/exec/write into Documents from launchd.
cat >"$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by install-bulk-watchdog.sh — do not edit by hand.
set -eo pipefail
ROOT="${ROOT}"
SYS_LOG="${SYS_LOG}"
SYS_PAUSE="${SYS_PAUSE}"
SYS_COOLDOWN="${SYS_COOLDOWN}"
COOLDOWN_SEC="\${WATCHDOG_COOLDOWN_SEC:-600}"

log() {
  echo "\$(date -u +%Y-%m-%dT%H:%M:%SZ) \$*" >>"\$SYS_LOG" 2>/dev/null || true
}

# Hardcoded absolute ROOT only — never dirname. Do not probe ~/Documents from launchd (TCC).
if [[ -z "\$ROOT" ]]; then
  log "FATAL empty ROOT; refusing Terminal restart"
  exit 1
fi

if [[ -f "\$SYS_PAUSE" ]]; then
  log "SKIP restart (pause file present: \$SYS_PAUSE)"
  exit 0
fi

if pgrep -f 'scripts/bulk-download.sh' >/dev/null 2>&1; then
  workers=\$(pgrep -fc 'yarn start' 2>/dev/null || echo 0)
  log "OK bulk running (yarn workers: \$workers; launchd path skips Documents stall check)"
  exit 0
fi

now=\$(date +%s)
if [[ -f "\$SYS_COOLDOWN" ]]; then
  last=\$(cat "\$SYS_COOLDOWN" 2>/dev/null || echo 0)
  if [[ "\$last" =~ ^[0-9]+\$ ]] && (( now - last < COOLDOWN_SEC )); then
    log "SKIP restart (bulk not running; cooldown \${COOLDOWN_SEC}s, last \$((now - last))s ago)"
    exit 0
  fi
fi

log "RESTART bulk not running — opening Terminal.app (ROOT=\$ROOT)"
echo "\$now" >"\$SYS_COOLDOWN"
osascript <<OSA
tell application "Terminal"
  do script "cd '\$ROOT' && ./scripts/pipeline-health.sh --fix-locks && node scripts/reconcile-queue.js && export SKIP_BACKFILL_ON_START=1 PARALLEL=2 && ./scripts/start-bulk-download.sh && sleep 3 && ./scripts/queue-status.sh --health && echo '' && echo 'Bulk running under caffeinate. Minimize this window.'"
end tell
OSA
log "RESTART issued via Terminal.app"
EOF
chmod +x "$LAUNCHER"

if ! bash -n "$LAUNCHER"; then
  echo "ERROR: launcher syntax check failed" >&2
  exit 1
fi
if ! grep -q "ROOT=\"${ROOT}\"" "$LAUNCHER"; then
  echo "ERROR: launcher missing hardcoded ROOT=${ROOT}" >&2
  exit 1
fi
if grep -E 'ROOT=.*dirname' "$LAUNCHER"; then
  echo "ERROR: launcher still derives ROOT from dirname (window-storm bug)" >&2
  exit 1
fi

# Pause smoke (Library path — launchd-readable)
touch "$SYS_PAUSE"
if ! "$LAUNCHER"; then
  echo "ERROR: launcher failed under pause smoke test" >&2
  exit 1
fi
if ! grep -q "pause file present" "$SYS_LOG"; then
  echo "ERROR: pause smoke did not log SKIP" >&2
  exit 1
fi

cat >"$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${LAUNCHER}</string>
  </array>
  <key>StartInterval</key>
  <integer>300</integer>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${SYS_LOG}</string>
  <key>StandardErrorPath</key>
  <string>${SYS_LOG}</string>
  <key>WorkingDirectory</key>
  <string>${HOME}</string>
</dict>
</plist>
EOF

launchctl bootout "gui/${UID_NUM}" "$PLIST" 2>/dev/null || true
launchctl bootstrap "gui/${UID_NUM}" "$PLIST"
launchctl enable "gui/${UID_NUM}/${LABEL}"
launchctl kickstart -k "gui/${UID_NUM}/${LABEL}"
sleep 2

LAST_EXIT="$(launchctl print "gui/${UID_NUM}/${LABEL}" 2>/dev/null | awk '/last exit code/ {print $4; exit}')"
if [[ "$LAST_EXIT" == "126" || "$LAST_EXIT" == "127" ]]; then
  echo "ERROR: launchd last exit code=$LAST_EXIT. Check $SYS_LOG" >&2
  exit 1
fi

# Mirror pause into repo logs for operator discoverability (best-effort)
ln -sf "$SYS_PAUSE" "$ROOT/logs/watchdog.pause" 2>/dev/null || true

echo "Installed $LABEL"
echo "  plist:    $PLIST"
echo "  launcher: $LAUNCHER"
echo "  repo:     $ROOT"
echo "  log:      $SYS_LOG"
echo "  last exit:$LAST_EXIT"
echo "  check:    launchctl print gui/${UID_NUM}/${LABEL}"
echo "  health:   $ROOT/scripts/queue-status.sh --health"
echo "  pause:    touch $SYS_PAUSE"
echo "  unpause:  rm -f $SYS_PAUSE"
echo "NOTE: pause file is currently present from install smoke. Remove it to allow auto-restart."
